export const INITIAL_COUNTRY_LIST: string[] = [
  'Russia',
  'Kazakhstan',
  'Belarus',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'China',
  'Japan',
  'Canada',
  'Australia',
  'Brazil',
  'India',
  'Italy',
  'Spain',
  'Mexico',
  'South Korea',
  'Netherlands',
  'Turkey',
  'Poland',
  'Sweden',
  'Switzerland',
  'Argentina',
  'South Africa',
  'Egypt',
];
