export const INITIAL_COUNTRY_LIST: string[] = [
  'russia',
  'kazakhstan',
  'belarus',
  'united states',
  'united kingdom',
  'germany',
  'france',
  'china',
  'japan',
  'canada',
  'australia',
  'brazil',
  'india',
  'italy',
  'spain',
  'mexico',
  'south korea',
  'netherlands',
  'turkey',
  'poland',
  'sweden',
  'switzerland',
  'argentina',
  'south africa',
  'egypt',
];
