export const INITIAL_GENDER_LIST: string[] = [
  'male',
  'female',
  'non-binary',
  'genderfluid',
  'agender',
  'bigender',
  'genderqueer',
  'transgender',
  'intersex',
  'two-spirit',
  'secret',

  ':3',
  'attack helicopter',
  'fishing boat',
  'a пятёрочка bag',
  'a toaster',
  'potato',
  'rizzler',
  'catgirl',
  "schrödinger's gender",
  'neural network',
];
